SELECT count(ordernumber) as total_orders,
       customernumber
FROM orders
where status = 'On Hold'
GROUP BY customernumber
ORDER BY customernumber;
Earlier code

Modified
WITH df AS
(
  SELECT c.customernumber,
         COUNT(o.ordernumber) AS total_orders
  FROM orders o
    RIGHT JOIN customers c ON o.customernumber = c.customernumber
  WHERE o.status = 'On Hold'
 -- OR    o.status IS NULL
  GROUP BY c.customernumber
  ORDER BY c.customernumber
)

   
SELECT c.customernumber,
       count(df.total_orders)as totalorders
FROM customers c
  left JOIN df ON c.customernumber = df.customernumber 

group by c.customernumber
order by count(df.total_orders) desc;






51.List the names of customers and their corresponding order number where a particular order from that customer has a value greater than $25,000?
SELECT c.customername,
       o.ordernumber
FROM customers c
  INNER JOIN orders o ON c.customernumber = o.customernumber
  INNER JOIN orderdetails od ON o.ordernumber = od.ordernumber
GROUP BY o.ordernumber,
         c.customername
HAVING SUM(od.priceeach*od.quantityordered) > 25000;



52.. Compute the commission for each sales representative, assuming the commission is 5% of the value of an order. Sort by employee last name and first name.


SELECT e.firstname,
       e.lastname,
       e.employeenumber,
       SUM(od.priceeach*od.quantityordered)*0.05 AS commission
FROM employees e
  INNER JOIN customers c ON e.employeenumber = c.salesrepemployeenumber
  INNER JOIN orders o ON c.customernumber = o.customernumber
  INNER JOIN orderdetails od ON o.ordernumber = od.ordernumber
GROUP BY e.employeenumber,e.lastname,e.firstname;


53.Compute the average time between order date and ship date for each customer ordered by the largest difference
SELECT AVG(shippeddate - orderdate) AS days,
       customernumber
FROM orders
GROUP BY customernumber
ORDER BY days DESC;



54.Compute the revenue generated by each sales representative based on the orders from the customers they serve.
SELECT SUM(od.priceeach*od.quantityordered) AS revenue,
       c.salesrepemployeenumber
FROM employees e
  INNER JOIN customers c ON e.employeenumber = c.salesrepemployeenumber
  INNER JOIN orders o ON c.customernumber = o.customernumber
  INNER JOIN orderdetails od ON o.ordernumber = od.ordernumber
GROUP BY c.salesrepemployeenumber;