SELECT SUM((od.priceeach-p.buyprice)*od.quantityordered) AS profit,
       c.salesrepemployeenumber
FROM employees e
  INNER JOIN customers c ON e.employeenumber = c.salesrepemployeenumber
  INNER JOIN orders o ON c.customernumber = o.customernumber
  INNER JOIN orderdetails od ON o.ordernumber = od.ordernumber
  INNER JOIN products p ON od.productcode = p.productcode
GROUP BY c.salesrepemployeenumber
ORDER BY SUM((od.priceeach-p.buyprice)*od.quantityordered) DESC;


56.Compute the revenue generated by each product, sorted by product name.
SELECT SUM(od.priceeach*od.quantityordered) AS revenue,
       p.productname
FROM orderdetails od
  INNER JOIN products p ON od.productcode = p.productcode
GROUP BY p.productname
ORDER BY p.productname;



57.Compute the profit generated by each product line, sorted by profit descending.
SELECT SUM((od.priceeach - p.buyprice)*od.quantityordered) AS profit,
       p.productline
FROM orderdetails od
  INNER JOIN products p ON od.productcode = p.productcode
GROUP BY p.productline
ORDER BY SUM((od.priceeach - p.buyprice)*od.quantityordered) DESC;



58..Compute the total value ordered, total amount paid, and their difference for each customer for orders placed in May 2004 and payments received in May 2004 (Hint; write separate queries for 'total paid' and 'total ordered' and join them .. you can use CTEs or Subqueries).
WITH tv AS
(
  SELECT SUM(od.priceeach*od.quantityordered) AS totalvalue,
         c.customernumber
  FROM orderdetails od
    RIGHT JOIN orders o ON od.ordernumber = o.ordernumber
    RIGHT JOIN customers c ON o.customernumber = c.customernumber
  WHERE EXTRACT(YEAR FROM o.orderdate) = 2004
  AND   EXTRACT(MONTH FROM o.orderdate) = 5
  GROUP BY c.customernumber
),
tp AS
(
  SELECT SUM(p.amount) AS totalpaid,
         c.customernumber
  FROM payments p
    FULL OUTER JOIN customers c ON p.customernumber = c.customernumber
  WHERE EXTRACT(YEAR FROM p.paymentdate) = 2004
  AND   EXTRACT(MONTH FROM p.paymentdate) = 5
  GROUP BY c.customernumber
)
SELECT DISTINCT coalesce(tp.customernumber,tv.customernumber)as customernumber,
       totalvalue,
       totalpaid,
       CASE
         WHEN totalvalue IS NOT NULL AND totalpaid IS NOT NULL THEN (totalpaid - totalvalue)
         WHEN totalpaid IS NULL THEN- totalvalue
         WHEN totalvalue IS NULL THEN totalpaid
       END AS difference
FROM tp
  FULL OUTER JOIN tv ON tp.customernumber = tv.customernumber
ORDER BY coalesce(tp.customernumber,tv.customernumber);



59.What is the ratio the value of payments made to orders received for each month of 2004. (i.e., divide the value of payments made by the orders received)?
with tp as
(
select extract(MONTH from paymentdate)as m,sum(amount)as totalpaid
from payments
where extract(YEAR from paymentdate)=2004
group by extract(MONTH from paymentdate)
),
tv as
(
select extract(MONTH from o.orderdate)as m,sum(od.priceeach*od.quantityordered)as totalvalue
from orderdetails od inner join orders o on od.ordernumber=o.ordernumber
where extract(YEAR from o.orderdate)=2004
group by extract(MONTH from o.orderdate)
)

select tv.m,sum(tp.totalpaid)/sum(tv.totalvalue)as ratio,sum(tp.totalpaid) as paid_amt,
sum(tv.totalvalue)as order_amt
from tv inner join tp on tv.m=tp.m
group by tv.m
order by tv.m;




60.What is the difference in the amount received for each month of 2004 compared to 2003?
WITH tp2004 AS
(
  SELECT EXTRACT(MONTH FROM paymentdate) AS m,
         SUM(amount) AS totalpaid
  FROM payments
  WHERE EXTRACT(YEAR FROM paymentdate) = 2004
  GROUP BY EXTRACT(MONTH FROM paymentdate)
),
tp2003 AS
(
  SELECT EXTRACT(MONTH FROM paymentdate) AS m,
         SUM(amount) AS totalpaid
         FROM payments
  WHERE EXTRACT(YEAR FROM paymentdate) = 2003
  GROUP BY EXTRACT(MONTH FROM paymentdate)
)
SELECT (tp2004.totalpaid - tp2003.totalpaid) AS diffrence,
       tp2004.m
FROM tp2004
  INNER JOIN tp2003 ON tp2004.m = tp2003.m;


61.Compute the ratio for each product of sales for 2003 versus 2004
WITH proc2004 AS
(
  SELECT p.productname,
         SUM(od.quantityordered*od.priceeach) AS sales
  FROM products p
    INNER JOIN orderdetails od ON p.productcode = od.productcode
    INNER JOIN orders o ON od.ordernumber = o.ordernumber
  WHERE EXTRACT(YEAR FROM o.orderdate) = 2004
  GROUP BY p.productname
),
proc2003 AS
(
  SELECT p.productname,
         SUM(od.quantityordered*od.priceeach) AS sales
  FROM products p
    INNER JOIN orderdetails od ON p.productcode = od.productcode
    INNER JOIN orders o ON od.ordernumber = o.ordernumber
  WHERE EXTRACT(YEAR FROM o.orderdate) = 2003
  GROUP BY p.productname
)
SELECT (proc2003.sales / proc2004.sales) AS ratio_sales,
       proc2004.productname
FROM proc2004
  INNER JOIN proc2003 ON proc2004.productname = proc2003.productname;