SELECT SUM(Prod.QUANTITYINSTOCK) AS ON_HAND_QUANTITY
FROM PRODUCTS Prod
  JOIN ORDERDETAILS OD ON Prod.PRODUCTCODE = OD.PRODUCTCODE
  JOIN ORDERS O ON OD.ORDERNUMBER = O.ORDERNUMBER
WHERE O.STATUS = 'On Hold’