CREATE TABLE products as ( SELECT * FROM classicmodels.products);
CREATE OR REPLACE PROCEDURE increase_price(
CATEGORY_INC IN VARCHAR2,
PERCENTAGE_INC IN NUMBER
)
IS
BEGIN
UPDATE PRODUCTS
SET MSRP = MSRP + (MSRP * (PERCENTAGE_INC / 100))
WHERE lower(PRODUCTLINE) = CATEGORY_INC;

COMMIT;
END;
/