72: Write a procedure to change the credit limit of all customers in a specified country by a specified percentage.
CREATE TABLE CUSTOMERS 
AS
SELECT *
FROM CLASSICMODELS.CUSTOMERS;
CREATE OR REPLACE PROCEDURE CHANGECREDIT (Perc NUMBER,COUNTY VARCHAR2) IS BEGIN UPDATE CUSTOMERS
   SET CREDITLIMIT = CREDITLIMIT +(CREDITLIMIT*Perc) / 100
WHERE COUNTRY = COUNTY;

COMMIT;

END;
/

DROP TABLE CUSTOMERS;
ALTER SESSION
   SET CURRENT_SCHEMA = classicmodels;